export const jobData = [
    {
      id: "1",
      title: "Frontend Developer",
      company: "TechCorp",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Full-time",
      salary: 95000,
      experience: "Mid-level",
      postedDate: "2025-03-10",
      description:
        "We're looking for a talented Frontend Developer to join our team. You'll be responsible for building user interfaces for our web applications using React and TypeScript.",
      requirements: [
        "3+ years of experience with React",
        "Strong knowledge of JavaScript and TypeScript",
        "Experience with responsive design and CSS frameworks",
        "Familiarity with modern frontend build tools",
        "Good understanding of web accessibility standards",
      ],
      benefits: [
        "Competitive salary and equity",
        "Health, dental, and vision insurance",
        "Flexible work hours and remote work options",
        "Professional development budget",
        "Regular team events and retreats",
      ],
    },
    {
      id: "2",
      title: "Full Stack Engineer",
      company: "GrowthStartup",
      logo: "/placeholder.svg?height=48&width=48",
      location: "San Francisco",
      type: "Full-time",
      salary: 120000,
      experience: "Senior",
      postedDate: "2025-03-15",
      description:
        "Join our fast-growing startup as a Full Stack Engineer. You'll work on both frontend and backend development, helping to build and scale our platform.",
      requirements: [
        "5+ years of experience in full stack development",
        "Proficiency in React, Node.js, and TypeScript",
        "Experience with database design and optimization",
        "Knowledge of cloud services (AWS, GCP, or Azure)",
        "Strong problem-solving skills and attention to detail",
      ],
      benefits: [
        "Competitive salary and equity package",
        "Comprehensive health benefits",
        "Flexible work arrangements",
        "Unlimited PTO",
        "Home office stipend",
      ],
    },
    {
      id: "3",
      title: "UI/UX Designer",
      company: "DesignHub",
      logo: "/placeholder.svg?height=48&width=48",
      location: "New York",
      type: "Full-time",
      salary: 85000,
      experience: "Mid-level",
      postedDate: "2025-03-12",
      description:
        "We're seeking a talented UI/UX Designer to create beautiful, intuitive interfaces for our products. You'll work closely with our product and engineering teams to deliver exceptional user experiences.",
      requirements: [
        "3+ years of experience in UI/UX design",
        "Proficiency in design tools like Figma or Sketch",
        "Strong portfolio demonstrating your design process",
        "Experience with user research and usability testing",
        "Knowledge of design systems and component libraries",
      ],
      benefits: [
        "Competitive salary",
        "Health and wellness benefits",
        "Flexible work hours",
        "Creative environment",
        "Professional development opportunities",
      ],
    },
    {
      id: "4",
      title: "Backend Developer",
      company: "DataSystems",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Berlin",
      type: "Full-time",
      salary: 90000,
      experience: "Senior",
      postedDate: "2025-03-08",
      description:
        "Join our backend team to build scalable and reliable services. You'll be working on our core infrastructure, designing APIs, and optimizing database performance.",
      requirements: [
        "5+ years of experience in backend development",
        "Strong knowledge of Node.js, Python, or Java",
        "Experience with database systems (SQL and NoSQL)",
        "Understanding of microservices architecture",
        "Knowledge of cloud infrastructure and deployment",
      ],
      benefits: [
        "Competitive compensation",
        "Comprehensive benefits package",
        "Remote work options",
        "Continuous learning opportunities",
        "International team environment",
      ],
    },
    {
      id: "5",
      title: "DevOps Engineer",
      company: "CloudTech",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Contract",
      salary: 110000,
      experience: "Senior",
      postedDate: "2025-03-16",
      description:
        "We're looking for a DevOps Engineer to help us build and maintain our cloud infrastructure. You'll be responsible for automation, CI/CD pipelines, and ensuring the reliability of our systems.",
      requirements: [
        "4+ years of experience in DevOps or SRE roles",
        "Strong knowledge of cloud platforms (AWS, GCP, or Azure)",
        "Experience with containerization and orchestration (Docker, Kubernetes)",
        "Proficiency in infrastructure as code (Terraform, CloudFormation)",
        "Understanding of monitoring and observability tools",
      ],
      benefits: [
        "Competitive hourly rate",
        "Flexible working hours",
        "Remote-first culture",
        "Learning and development budget",
        "Opportunity for long-term collaboration",
      ],
    },
    {
      id: "6",
      title: "Product Manager",
      company: "InnovateCo",
      logo: "/placeholder.svg?height=48&width=48",
      location: "London",
      type: "Full-time",
      salary: 105000,
      experience: "Lead",
      postedDate: "2025-03-05",
      description:
        "Join our product team as a Product Manager to drive the development of innovative solutions. You'll work closely with design, engineering, and marketing teams to deliver products that delight our customers.",
      requirements: [
        "5+ years of experience in product management",
        "Strong understanding of product development lifecycle",
        "Experience with agile methodologies",
        "Excellent communication and stakeholder management skills",
        "Data-driven approach to decision making",
      ],
      benefits: [
        "Competitive salary and bonus",
        "Comprehensive benefits package",
        "Flexible working arrangements",
        "Professional development opportunities",
        "International travel opportunities",
      ],
    },
    {
      id: "7",
      title: "Mobile Developer",
      company: "AppWorks",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Full-time",
      salary: 95000,
      experience: "Mid-level",
      postedDate: "2025-03-14",
      description:
        "We're seeking a talented Mobile Developer to join our team. You'll be responsible for developing and maintaining our mobile applications for iOS and Android platforms.",
      requirements: [
        "3+ years of experience in mobile development",
        "Proficiency in React Native or Flutter",
        "Experience with native development (Swift or Kotlin) is a plus",
        "Understanding of mobile UI/UX principles",
        "Knowledge of app store submission processes",
      ],
      benefits: [
        "Competitive salary",
        "Health and wellness benefits",
        "Remote work options",
        "Flexible schedule",
        "Latest equipment and tools",
      ],
    },
    {
      id: "8",
      title: "Data Scientist",
      company: "AnalyticsPro",
      logo: "/placeholder.svg?height=48&width=48",
      location: "New York",
      type: "Full-time",
      salary: 115000,
      experience: "Senior",
      postedDate: "2025-03-07",
      description:
        "Join our data science team to extract insights from complex datasets. You'll be working on machine learning models, statistical analysis, and data visualization to drive business decisions.",
      requirements: [
        "4+ years of experience in data science or related field",
        "Strong background in statistics and machine learning",
        "Proficiency in Python and data analysis libraries",
        "Experience with big data technologies",
        "Excellent communication skills to present findings to non-technical stakeholders",
      ],
      benefits: [
        "Competitive compensation package",
        "Comprehensive health benefits",
        "Flexible work arrangements",
        "Continuing education support",
        "Regular team events and workshops",
      ],
    },
    {
      id: "9",
      title: "QA Engineer",
      company: "QualitySoft",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Berlin",
      type: "Full-time",
      salary: 80000,
      experience: "Entry-level",
      postedDate: "2025-03-17",
      description:
        "We're looking for a detail-oriented QA Engineer to ensure the quality of our software products. You'll be responsible for manual and automated testing, identifying bugs, and collaborating with developers to resolve issues.",
      requirements: [
        "1-2 years of experience in software testing",
        "Knowledge of testing methodologies and best practices",
        "Experience with test automation frameworks",
        "Basic understanding of web technologies",
        "Strong attention to detail and problem-solving skills",
      ],
      benefits: [
        "Competitive salary",
        "Health insurance",
        "Flexible working hours",
        "Professional development opportunities",
        "Modern office environment",
      ],
    },
    {
      id: "10",
      title: "Technical Writer",
      company: "DocuTech",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Part-time",
      salary: 65000,
      experience: "Mid-level",
      postedDate: "2025-03-11",
      description:
        "Join our documentation team as a Technical Writer to create clear, concise, and comprehensive documentation for our software products. You'll work closely with developers, product managers, and support teams to ensure our users have the information they need.",
      requirements: [
        "2+ years of experience in technical writing",
        "Strong writing and editing skills",
        "Ability to understand complex technical concepts",
        "Experience with documentation tools and platforms",
        "Knowledge of information architecture and content strategy",
      ],
      benefits: [
        "Competitive hourly rate",
        "Flexible schedule",
        "Remote work",
        "Professional development opportunities",
        "Collaborative team environment",
      ],
    },
    {
      id: "11",
      title: "Technical Writer",
      company: "DocuTech",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Part-time",
      salary: 65000,
      experience: "Mid-level",
      postedDate: "2025-03-11",
      description:
        "Join our documentation team as a Technical Writer to create clear, concise, and comprehensive documentation for our software products. You'll work closely with developers, product managers, and support teams to ensure our users have the information they need.",
      requirements: [
        "2+ years of experience in technical writing",
        "Strong writing and editing skills",
        "Ability to understand complex technical concepts",
        "Experience with documentation tools and platforms",
        "Knowledge of information architecture and content strategy",
      ],
      benefits: [
        "Competitive hourly rate",
        "Flexible schedule",
        "Remote work",
        "Professional development opportunities",
        "Collaborative team environment",
      ],
    },
    {
      id: "1",
      title: "Frontend Developer",
      company: "TechCorp",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Full-time",
      salary: 95000,
      experience: "Mid-level",
      postedDate: "2025-03-10",
      description:
        "We're looking for a talented Frontend Developer to join our team. You'll be responsible for building user interfaces for our web applications using React and TypeScript.",
      requirements: [
        "3+ years of experience with React",
        "Strong knowledge of JavaScript and TypeScript",
        "Experience with responsive design and CSS frameworks",
        "Familiarity with modern frontend build tools",
        "Good understanding of web accessibility standards",
      ],
      benefits: [
        "Competitive salary and equity",
        "Health, dental, and vision insurance",
        "Flexible work hours and remote work options",
        "Professional development budget",
        "Regular team events and retreats",
      ],
    },
    {
      id: "2",
      title: "Full Stack Engineer",
      company: "GrowthStartup",
      logo: "/placeholder.svg?height=48&width=48",
      location: "San Francisco",
      type: "Full-time",
      salary: 120000,
      experience: "Senior",
      postedDate: "2025-03-15",
      description:
        "Join our fast-growing startup as a Full Stack Engineer. You'll work on both frontend and backend development, helping to build and scale our platform.",
      requirements: [
        "5+ years of experience in full stack development",
        "Proficiency in React, Node.js, and TypeScript",
        "Experience with database design and optimization",
        "Knowledge of cloud services (AWS, GCP, or Azure)",
        "Strong problem-solving skills and attention to detail",
      ],
      benefits: [
        "Competitive salary and equity package",
        "Comprehensive health benefits",
        "Flexible work arrangements",
        "Unlimited PTO",
        "Home office stipend",
      ],
    },
    {
      id: "3",
      title: "UI/UX Designer",
      company: "DesignHub",
      logo: "/placeholder.svg?height=48&width=48",
      location: "New York",
      type: "Full-time",
      salary: 85000,
      experience: "Mid-level",
      postedDate: "2025-03-12",
      description:
        "We're seeking a talented UI/UX Designer to create beautiful, intuitive interfaces for our products. You'll work closely with our product and engineering teams to deliver exceptional user experiences.",
      requirements: [
        "3+ years of experience in UI/UX design",
        "Proficiency in design tools like Figma or Sketch",
        "Strong portfolio demonstrating your design process",
        "Experience with user research and usability testing",
        "Knowledge of design systems and component libraries",
      ],
      benefits: [
        "Competitive salary",
        "Health and wellness benefits",
        "Flexible work hours",
        "Creative environment",
        "Professional development opportunities",
      ],
    },
    {
      id: "4",
      title: "Backend Developer",
      company: "DataSystems",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Berlin",
      type: "Full-time",
      salary: 90000,
      experience: "Senior",
      postedDate: "2025-03-08",
      description:
        "Join our backend team to build scalable and reliable services. You'll be working on our core infrastructure, designing APIs, and optimizing database performance.",
      requirements: [
        "5+ years of experience in backend development",
        "Strong knowledge of Node.js, Python, or Java",
        "Experience with database systems (SQL and NoSQL)",
        "Understanding of microservices architecture",
        "Knowledge of cloud infrastructure and deployment",
      ],
      benefits: [
        "Competitive compensation",
        "Comprehensive benefits package",
        "Remote work options",
        "Continuous learning opportunities",
        "International team environment",
      ],
    },
    {
      id: "5",
      title: "DevOps Engineer",
      company: "CloudTech",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Contract",
      salary: 110000,
      experience: "Senior",
      postedDate: "2025-03-16",
      description:
        "We're looking for a DevOps Engineer to help us build and maintain our cloud infrastructure. You'll be responsible for automation, CI/CD pipelines, and ensuring the reliability of our systems.",
      requirements: [
        "4+ years of experience in DevOps or SRE roles",
        "Strong knowledge of cloud platforms (AWS, GCP, or Azure)",
        "Experience with containerization and orchestration (Docker, Kubernetes)",
        "Proficiency in infrastructure as code (Terraform, CloudFormation)",
        "Understanding of monitoring and observability tools",
      ],
      benefits: [
        "Competitive hourly rate",
        "Flexible working hours",
        "Remote-first culture",
        "Learning and development budget",
        "Opportunity for long-term collaboration",
      ],
    },
    {
      id: "6",
      title: "Product Manager",
      company: "InnovateCo",
      logo: "/placeholder.svg?height=48&width=48",
      location: "London",
      type: "Full-time",
      salary: 105000,
      experience: "Lead",
      postedDate: "2025-03-05",
      description:
        "Join our product team as a Product Manager to drive the development of innovative solutions. You'll work closely with design, engineering, and marketing teams to deliver products that delight our customers.",
      requirements: [
        "5+ years of experience in product management",
        "Strong understanding of product development lifecycle",
        "Experience with agile methodologies",
        "Excellent communication and stakeholder management skills",
        "Data-driven approach to decision making",
      ],
      benefits: [
        "Competitive salary and bonus",
        "Comprehensive benefits package",
        "Flexible working arrangements",
        "Professional development opportunities",
        "International travel opportunities",
      ],
    },
    {
      id: "7",
      title: "Mobile Developer",
      company: "AppWorks",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Full-time",
      salary: 95000,
      experience: "Mid-level",
      postedDate: "2025-03-14",
      description:
        "We're seeking a talented Mobile Developer to join our team. You'll be responsible for developing and maintaining our mobile applications for iOS and Android platforms.",
      requirements: [
        "3+ years of experience in mobile development",
        "Proficiency in React Native or Flutter",
        "Experience with native development (Swift or Kotlin) is a plus",
        "Understanding of mobile UI/UX principles",
        "Knowledge of app store submission processes",
      ],
      benefits: [
        "Competitive salary",
        "Health and wellness benefits",
        "Remote work options",
        "Flexible schedule",
        "Latest equipment and tools",
      ],
    },
    {
      id: "8",
      title: "Data Scientist",
      company: "AnalyticsPro",
      logo: "/placeholder.svg?height=48&width=48",
      location: "New York",
      type: "Full-time",
      salary: 115000,
      experience: "Senior",
      postedDate: "2025-03-07",
      description:
        "Join our data science team to extract insights from complex datasets. You'll be working on machine learning models, statistical analysis, and data visualization to drive business decisions.",
      requirements: [
        "4+ years of experience in data science or related field",
        "Strong background in statistics and machine learning",
        "Proficiency in Python and data analysis libraries",
        "Experience with big data technologies",
        "Excellent communication skills to present findings to non-technical stakeholders",
      ],
      benefits: [
        "Competitive compensation package",
        "Comprehensive health benefits",
        "Flexible work arrangements",
        "Continuing education support",
        "Regular team events and workshops",
      ],
    },
    {
      id: "9",
      title: "QA Engineer",
      company: "QualitySoft",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Berlin",
      type: "Full-time",
      salary: 80000,
      experience: "Entry-level",
      postedDate: "2025-03-17",
      description:
        "We're looking for a detail-oriented QA Engineer to ensure the quality of our software products. You'll be responsible for manual and automated testing, identifying bugs, and collaborating with developers to resolve issues.",
      requirements: [
        "1-2 years of experience in software testing",
        "Knowledge of testing methodologies and best practices",
        "Experience with test automation frameworks",
        "Basic understanding of web technologies",
        "Strong attention to detail and problem-solving skills",
      ],
      benefits: [
        "Competitive salary",
        "Health insurance",
        "Flexible working hours",
        "Professional development opportunities",
        "Modern office environment",
      ],
    },
    {
      id: "10",
      title: "Technical Writer",
      company: "DocuTech",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Part-time",
      salary: 65000,
      experience: "Mid-level",
      postedDate: "2025-03-11",
      description:
        "Join our documentation team as a Technical Writer to create clear, concise, and comprehensive documentation for our software products. You'll work closely with developers, product managers, and support teams to ensure our users have the information they need.",
      requirements: [
        "2+ years of experience in technical writing",
        "Strong writing and editing skills",
        "Ability to understand complex technical concepts",
        "Experience with documentation tools and platforms",
        "Knowledge of information architecture and content strategy",
      ],
      benefits: [
        "Competitive hourly rate",
        "Flexible schedule",
        "Remote work",
        "Professional development opportunities",
        "Collaborative team environment",
      ],
    },
    {
      id: "11",
      title: "Technical Writer",
      company: "DocuTech",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Part-time",
      salary: 65000,
      experience: "Mid-level",
      postedDate: "2025-03-11",
      description:
        "Join our documentation team as a Technical Writer to create clear, concise, and comprehensive documentation for our software products. You'll work closely with developers, product managers, and support teams to ensure our users have the information they need.",
      requirements: [
        "2+ years of experience in technical writing",
        "Strong writing and editing skills",
        "Ability to understand complex technical concepts",
        "Experience with documentation tools and platforms",
        "Knowledge of information architecture and content strategy",
      ],
      benefits: [
        "Competitive hourly rate",
        "Flexible schedule",
        "Remote work",
        "Professional development opportunities",
        "Collaborative team environment",
      ],
    },
  ]
  
  