export const jobData = [
    {
      id: "1",
      title: "Frontend Developer",
      company: "TechCorp",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Full-time",
      salary: 95000,
      experience: "Mid-level",
      postedDate: "2025-03-10",
      description:
        "We're looking for a talented Frontend Developer to join our team. You'll be responsible for building user interfaces for our web applications using React and TypeScript.",
      requirements: [
        "3+ years of experience with React",
        "Strong knowledge of JavaScript and TypeScript",
        "Experience with responsive design and CSS frameworks",
        "Familiarity with modern frontend build tools",
        "Good understanding of web accessibility standards",
      ],
      benefits: [
        "Competitive salary and equity",
        "Health, dental, and vision insurance",
        "Flexible work hours and remote work options",
        "Professional development budget",
        "Regular team events and retreats",
      ],
    },
    {
      id: "2",
      title: "Full Stack Engineer",
      company: "GrowthStartup",
      logo: "/placeholder.svg?height=48&width=48",
      location: "San Francisco",
      type: "Full-time",
      salary: 120000,
      experience: "Senior",
      postedDate: "2025-03-15",
      description:
        "Join our fast-growing startup as a Full Stack Engineer. You'll work on both frontend and backend development, helping to build and scale our platform.",
      requirements: [
        "5+ years of experience in full stack development",
        "Proficiency in React, Node.js, and TypeScript",
        "Experience with database design and optimization",
        "Knowledge of cloud services (AWS, GCP, or Azure)",
        "Strong problem-solving skills and attention to detail",
      ],
      benefits: [
        "Competitive salary and equity package",
        "Comprehensive health benefits",
        "Flexible work arrangements",
        "Unlimited PTO",
        "Home office stipend",
      ],
    },
    {
      id: "3",
      title: "UI/UX Designer",
      company: "DesignHub",
      logo: "/placeholder.svg?height=48&width=48",
      location: "New York",
      type: "Full-time",
      salary: 85000,
      experience: "Mid-level",
      postedDate: "2025-03-12",
      description:
        "We're seeking a talented UI/UX Designer to create beautiful, intuitive interfaces for our products. You'll work closely with our product and engineering teams to deliver exceptional user experiences.",
      requirements: [
        "3+ years of experience in UI/UX design",
        "Proficiency in design tools like Figma or Sketch",
        "Strong portfolio demonstrating your design process",
        "Experience with user research and usability testing",
        "Knowledge of design systems and component libraries",
      ],
      benefits: [
        "Competitive salary",
        "Health and wellness benefits",
        "Flexible work hours",
        "Creative environment",
        "Professional development opportunities",
      ],
    },
    {
      id: "4",
      title: "Backend Developer",
      company: "DataSystems",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Berlin",
      type: "Full-time",
      salary: 90000,
      experience: "Senior",
      postedDate: "2025-03-08",
      description:
        "Join our backend team to build scalable and reliable services. You'll be working on our core infrastructure, designing APIs, and optimizing database performance.",
      requirements: [
        "5+ years of experience in backend development",
        "Strong knowledge of Node.js, Python, or Java",
        "Experience with database systems (SQL and NoSQL)",
        "Understanding of microservices architecture",
        "Knowledge of cloud infrastructure and deployment",
      ],
      benefits: [
        "Competitive compensation",
        "Comprehensive benefits package",
        "Remote work options",
        "Continuous learning opportunities",
        "International team environment",
      ],
    },
    {
      id: "5",
      title: "DevOps Engineer",
      company: "CloudTech",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Contract",
      salary: 110000,
      experience: "Senior",
      postedDate: "2025-03-16",
      description:
        "We're looking for a DevOps Engineer to help us build and maintain our cloud infrastructure. You'll be responsible for automation, CI/CD pipelines, and ensuring the reliability of our systems.",
      requirements: [
        "4+ years of experience in DevOps or SRE roles",
        "Strong knowledge of cloud platforms (AWS, GCP, or Azure)",
        "Experience with containerization and orchestration (Docker, Kubernetes)",
        "Proficiency in infrastructure as code (Terraform, CloudFormation)",
        "Understanding of monitoring and observability tools",
      ],
      benefits: [
        "Competitive hourly rate",
        "Flexible working hours",
        "Remote-first culture",
        "Learning and development budget",
        "Opportunity for long-term collaboration",
      ],
    },
    {
      id: "6",
      title: "Product Manager",
      company: "InnovateCo",
      logo: "/placeholder.svg?height=48&width=48",
      location: "London",
      type: "Full-time",
      salary: 105000,
      experience: "Lead",
      postedDate: "2025-03-05",
      description:
        "Join our product team as a Product Manager to drive the development of innovative solutions. You'll work closely with design, engineering, and marketing teams to deliver products that delight our customers.",
      requirements: [
        "5+ years of experience in product management",
        "Strong understanding of product development lifecycle",
        "Experience with agile methodologies",
        "Excellent communication and stakeholder management skills",
        "Data-driven approach to decision making",
      ],
      benefits: [
        "Competitive salary and bonus",
        "Comprehensive benefits package",
        "Flexible working arrangements",
        "Professional development opportunities",
        "International travel opportunities",
      ],
    },
    {
      id: "7",
      title: "Mobile Developer",
      company: "AppWorks",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Full-time",
      salary: 95000,
      experience: "Mid-level",
      postedDate: "2025-03-14",
      description:
        "We're seeking a talented Mobile Developer to join our team. You'll be responsible for developing and maintaining our mobile applications for iOS and Android platforms.",
      requirements: [
        "3+ years of experience in mobile development",
        "Proficiency in React Native or Flutter",
        "Experience with native development (Swift or Kotlin) is a plus",
        "Understanding of mobile UI/UX principles",
        "Knowledge of app store submission processes",
      ],
      benefits: [
        "Competitive salary",
        "Health and wellness benefits",
        "Remote work options",
        "Flexible schedule",
        "Latest equipment and tools",
      ],
    },
    {
      id: "8",
      title: "Data Scientist",
      company: "AnalyticsPro",
      logo: "/placeholder.svg?height=48&width=48",
      location: "New York",
      type: "Full-time",
      salary: 115000,
      experience: "Senior",
      postedDate: "2025-03-07",
      description:
        "Join our data science team to extract insights from complex datasets. You'll be working on machine learning models, statistical analysis, and data visualization to drive business decisions.",
      requirements: [
        "4+ years of experience in data science or related field",
        "Strong background in statistics and machine learning",
        "Proficiency in Python and data analysis libraries",
        "Experience with big data technologies",
        "Excellent communication skills to present findings to non-technical stakeholders",
      ],
      benefits: [
        "Competitive compensation package",
        "Comprehensive health benefits",
        "Flexible work arrangements",
        "Continuing education support",
        "Regular team events and workshops",
      ],
    },
    {
      id: "9",
      title: "QA Engineer",
      company: "QualitySoft",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Berlin",
      type: "Full-time",
      salary: 80000,
      experience: "Entry-level",
      postedDate: "2025-03-17",
      description:
        "We're looking for a detail-oriented QA Engineer to ensure the quality of our software products. You'll be responsible for manual and automated testing, identifying bugs, and collaborating with developers to resolve issues.",
      requirements: [
        "1-2 years of experience in software testing",
        "Knowledge of testing methodologies and best practices",
        "Experience with test automation frameworks",
        "Basic understanding of web technologies",
        "Strong attention to detail and problem-solving skills",
      ],
      benefits: [
        "Competitive salary",
        "Health insurance",
        "Flexible working hours",
        "Professional development opportunities",
        "Modern office environment",
      ],
    },
    {
      id: "10",
      title: "Technical Writer",
      company: "DocuTech",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Part-time",
      salary: 65000,
      experience: "Mid-level",
      postedDate: "2025-03-11",
      description:
        "Join our documentation team as a Technical Writer to create clear, concise, and comprehensive documentation for our software products. You'll work closely with developers, product managers, and support teams to ensure our users have the information they need.",
      requirements: [
        "2+ years of experience in technical writing",
        "Strong writing and editing skills",
        "Ability to understand complex technical concepts",
        "Experience with documentation tools and platforms",
        "Knowledge of information architecture and content strategy",
      ],
      benefits: [
        "Competitive hourly rate",
        "Flexible schedule",
        "Remote work",
        "Professional development opportunities",
        "Collaborative team environment",
      ],
    },
    {
      id: "11",
      title: "Technical Writer",
      company: "DocuTech",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Part-time",
      salary: 65000,
      experience: "Mid-level",
      postedDate: "2025-03-11",
      description:
        "Join our documentation team as a Technical Writer to create clear, concise, and comprehensive documentation for our software products. You'll work closely with developers, product managers, and support teams to ensure our users have the information they need.",
      requirements: [
        "2+ years of experience in technical writing",
        "Strong writing and editing skills",
        "Ability to understand complex technical concepts",
        "Experience with documentation tools and platforms",
        "Knowledge of information architecture and content strategy",
      ],
      benefits: [
        "Competitive hourly rate",
        "Flexible schedule",
        "Remote work",
        "Professional development opportunities",
        "Collaborative team environment",
      ],
    },
    {
      id: "1",
      title: "Frontend Developer",
      company: "TechCorp",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Full-time",
      salary: 95000,
      experience: "Mid-level",
      postedDate: "2025-03-10",
      description:
        "We're looking for a talented Frontend Developer to join our team. You'll be responsible for building user interfaces for our web applications using React and TypeScript.",
      requirements: [
        "3+ years of experience with React",
        "Strong knowledge of JavaScript and TypeScript",
        "Experience with responsive design and CSS frameworks",
        "Familiarity with modern frontend build tools",
        "Good understanding of web accessibility standards",
      ],
      benefits: [
        "Competitive salary and equity",
        "Health, dental, and vision insurance",
        "Flexible work hours and remote work options",
        "Professional development budget",
        "Regular team events and retreats",
      ],
    },
    {
      id: "2",
      title: "Full Stack Engineer",
      company: "GrowthStartup",
      logo: "/placeholder.svg?height=48&width=48",
      location: "San Francisco",
      type: "Full-time",
      salary: 120000,
      experience: "Senior",
      postedDate: "2025-03-15",
      description:
        "Join our fast-growing startup as a Full Stack Engineer. You'll work on both frontend and backend development, helping to build and scale our platform.",
      requirements: [
        "5+ years of experience in full stack development",
        "Proficiency in React, Node.js, and TypeScript",
        "Experience with database design and optimization",
        "Knowledge of cloud services (AWS, GCP, or Azure)",
        "Strong problem-solving skills and attention to detail",
      ],
      benefits: [
        "Competitive salary and equity package",
        "Comprehensive health benefits",
        "Flexible work arrangements",
        "Unlimited PTO",
        "Home office stipend",
      ],
    },
    {
      id: "3",
      title: "UI/UX Designer",
      company: "DesignHub",
      logo: "/placeholder.svg?height=48&width=48",
      location: "New York",
      type: "Full-time",
      salary: 85000,
      experience: "Mid-level",
      postedDate: "2025-03-12",
      description:
        "We're seeking a talented UI/UX Designer to create beautiful, intuitive interfaces for our products. You'll work closely with our product and engineering teams to deliver exceptional user experiences.",
      requirements: [
        "3+ years of experience in UI/UX design",
        "Proficiency in design tools like Figma or Sketch",
        "Strong portfolio demonstrating your design process",
        "Experience with user research and usability testing",
        "Knowledge of design systems and component libraries",
      ],
      benefits: [
        "Competitive salary",
        "Health and wellness benefits",
        "Flexible work hours",
        "Creative environment",
        "Professional development opportunities",
      ],
    },
    {
      id: "4",
      title: "Backend Developer",
      company: "DataSystems",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Berlin",
      type: "Full-time",
      salary: 90000,
      experience: "Senior",
      postedDate: "2025-03-08",
      description:
        "Join our backend team to build scalable and reliable services. You'll be working on our core infrastructure, designing APIs, and optimizing database performance.",
      requirements: [
        "5+ years of experience in backend development",
        "Strong knowledge of Node.js, Python, or Java",
        "Experience with database systems (SQL and NoSQL)",
        "Understanding of microservices architecture",
        "Knowledge of cloud infrastructure and deployment",
      ],
      benefits: [
        "Competitive compensation",
        "Comprehensive benefits package",
        "Remote work options",
        "Continuous learning opportunities",
        "International team environment",
      ],
    },
    {
      id: "5",
      title: "DevOps Engineer",
      company: "CloudTech",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Contract",
      salary: 110000,
      experience: "Senior",
      postedDate: "2025-03-16",
      description:
        "We're looking for a DevOps Engineer to help us build and maintain our cloud infrastructure. You'll be responsible for automation, CI/CD pipelines, and ensuring the reliability of our systems.",
      requirements: [
        "4+ years of experience in DevOps or SRE roles",
        "Strong knowledge of cloud platforms (AWS, GCP, or Azure)",
        "Experience with containerization and orchestration (Docker, Kubernetes)",
        "Proficiency in infrastructure as code (Terraform, CloudFormation)",
        "Understanding of monitoring and observability tools",
      ],
      benefits: [
        "Competitive hourly rate",
        "Flexible working hours",
        "Remote-first culture",
        "Learning and development budget",
        "Opportunity for long-term collaboration",
      ],
    },
    {
      id: "6",
      title: "Product Manager",
      company: "InnovateCo",
      logo: "/placeholder.svg?height=48&width=48",
      location: "London",
      type: "Full-time",
      salary: 105000,
      experience: "Lead",
      postedDate: "2025-03-05",
      description:
        "Join our product team as a Product Manager to drive the development of innovative solutions. You'll work closely with design, engineering, and marketing teams to deliver products that delight our customers.",
      requirements: [
        "5+ years of experience in product management",
        "Strong understanding of product development lifecycle",
        "Experience with agile methodologies",
        "Excellent communication and stakeholder management skills",
        "Data-driven approach to decision making",
      ],
      benefits: [
        "Competitive salary and bonus",
        "Comprehensive benefits package",
        "Flexible working arrangements",
        "Professional development opportunities",
        "International travel opportunities",
      ],
    },
    {
      id: "7",
      title: "Mobile Developer",
      company: "AppWorks",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Full-time",
      salary: 95000,
      experience: "Mid-level",
      postedDate: "2025-03-14",
      description:
        "We're seeking a talented Mobile Developer to join our team. You'll be responsible for developing and maintaining our mobile applications for iOS and Android platforms.",
      requirements: [
        "3+ years of experience in mobile development",
        "Proficiency in React Native or Flutter",
        "Experience with native development (Swift or Kotlin) is a plus",
        "Understanding of mobile UI/UX principles",
        "Knowledge of app store submission processes",
      ],
      benefits: [
        "Competitive salary",
        "Health and wellness benefits",
        "Remote work options",
        "Flexible schedule",
        "Latest equipment and tools",
      ],
    },
    {
      id: "8",
      title: "Data Scientist",
      company: "AnalyticsPro",
      logo: "/placeholder.svg?height=48&width=48",
      location: "New York",
      type: "Full-time",
      salary: 115000,
      experience: "Senior",
      postedDate: "2025-03-07",
      description:
        "Join our data science team to extract insights from complex datasets. You'll be working on machine learning models, statistical analysis, and data visualization to drive business decisions.",
      requirements: [
        "4+ years of experience in data science or related field",
        "Strong background in statistics and machine learning",
        "Proficiency in Python and data analysis libraries",
        "Experience with big data technologies",
        "Excellent communication skills to present findings to non-technical stakeholders",
      ],
      benefits: [
        "Competitive compensation package",
        "Comprehensive health benefits",
        "Flexible work arrangements",
        "Continuing education support",
        "Regular team events and workshops",
      ],
    },
    {
      id: "9",
      title: "QA Engineer",
      company: "QualitySoft",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Berlin",
      type: "Full-time",
      salary: 80000,
      experience: "Entry-level",
      postedDate: "2025-03-17",
      description:
        "We're looking for a detail-oriented QA Engineer to ensure the quality of our software products. You'll be responsible for manual and automated testing, identifying bugs, and collaborating with developers to resolve issues.",
      requirements: [
        "1-2 years of experience in software testing",
        "Knowledge of testing methodologies and best practices",
        "Experience with test automation frameworks",
        "Basic understanding of web technologies",
        "Strong attention to detail and problem-solving skills",
      ],
      benefits: [
        "Competitive salary",
        "Health insurance",
        "Flexible working hours",
        "Professional development opportunities",
        "Modern office environment",
      ],
    },
    {
      id: "10",
      title: "Technical Writer",
      company: "DocuTech",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Part-time",
      salary: 65000,
      experience: "Mid-level",
      postedDate: "2025-03-11",
      description:
        "Join our documentation team as a Technical Writer to create clear, concise, and comprehensive documentation for our software products. You'll work closely with developers, product managers, and support teams to ensure our users have the information they need.",
      requirements: [
        "2+ years of experience in technical writing",
        "Strong writing and editing skills",
        "Ability to understand complex technical concepts",
        "Experience with documentation tools and platforms",
        "Knowledge of information architecture and content strategy",
      ],
      benefits: [
        "Competitive hourly rate",
        "Flexible schedule",
        "Remote work",
        "Professional development opportunities",
        "Collaborative team environment",
      ],
    },
    {
      id: "11",
      title: "Technical Writer",
      company: "DocuTech",
      logo: "/placeholder.svg?height=48&width=48",
      location: "Remote",
      type: "Part-time",
      salary: 65000,
      experience: "Mid-level",
      postedDate: "2025-03-11",
      description:
        "Join our documentation team as a Technical Writer to create clear, concise, and comprehensive documentation for our software products. You'll work closely with developers, product managers, and support teams to ensure our users have the information they need.",
      requirements: [
        "2+ years of experience in technical writing",
        "Strong writing and editing skills",
        "Ability to understand complex technical concepts",
        "Experience with documentation tools and platforms",
        "Knowledge of information architecture and content strategy",
      ],
      benefits: [
        "Competitive hourly rate",
        "Flexible schedule",
        "Remote work",
        "Professional development opportunities",
        "Collaborative team environment",
      ],
    },
  ]
export const faqs = [
    {
        question: "What is the typical development timeline for a custom application?",
        answer:
            "Development timelines vary based on the complexity and scope of the project. Simple applications may take 2-3 months, while more complex enterprise solutions can take 6-12 months. During our initial consultation, we'll provide a detailed timeline based on your specific requirements.",
    },
    {
        question: "How do you ensure the security of custom applications?",
        answer:
            "Security is a top priority in all our development projects. We implement industry best practices including secure coding standards, encryption for sensitive data, regular security audits, penetration testing, and compliance with relevant regulations like GDPR or HIPAA depending on your industry.",
    },
    {
        question: "Can you provide examples of custom applications you've developed?",
        answer:
            "We've developed a wide range of custom applications across various industries, including healthcare management systems, e-commerce platforms with custom inventory management, financial services applications with complex reporting, and manufacturing process automation systems. We'd be happy to share relevant case studies during our consultation.",
    },
    {
        question: "Do you provide ongoing support after the application is launched?",
        answer:
            "Yes, we offer comprehensive support and maintenance packages to ensure your application continues to run smoothly. Our support includes bug fixes, security updates, performance optimization, and feature enhancements. We can tailor a support plan to meet your specific needs and budget.",
    },
    {
        question: "What technologies do you use for custom application development?",
        answer:
            "We work with a wide range of modern technologies based on project requirements. For web applications, we commonly use React, Angular, or Vue.js for frontend and Node.js, Python, or .NET for backend. For mobile, we develop native apps using Swift/Kotlin or cross-platform solutions with React Native or Flutter. Our technology recommendations are always based on your specific needs and long-term goals.",
    },
]

export const educationIndustory = [
  {
    title: "Learning Management System",
    description:
      "A comprehensive platform for course creation, student enrollment, assignment management, and progress tracking.",
    features: [
      "Interactive course content with multimedia support",
      "Automated grading and assessment tools",
      "Real-time analytics and reporting on student performance",
      "Virtual classroom with video conferencing integration",
      "Mobile-friendly access for learning on the go",
      "Discussion forums and collaborative learning tools",
    ],
  },
  {
    title: "School Management System",
    description:
      "An all-in-one solution for educational institutions to manage administrative tasks, student records, and academic processes.",
    features: [
      "Admission and enrollment management",
      "Attendance tracking and reporting",
      "Fee management and online payment integration",
      "Parent-teacher communication portal",
      "Timetable scheduling and management",
      "Exam management and result processing",
    ],
  },
  {
    title: "Educational Content Platform",
    description:
      "Digital platform for creating, distributing, and consuming educational content across various subjects and grade levels.",
    features: [
      "Interactive e-books and learning materials",
      "Gamified learning experiences with rewards",
      "Personalized learning paths based on student progress",
      "Content authoring tools for educators",
      "Offline access to downloaded content",
      "Integration with popular learning standards",
    ],
  },
]

export const healthIndustory = [
  {
    title: "Hospital Management System",
    description:
      "Comprehensive solution for hospitals to manage patient care, administrative tasks, and operational workflows.",
    features: [
      "Electronic Medical Records (EMR) management",
      "Patient appointment scheduling and reminders",
      "Billing and insurance claim processing",
      "Pharmacy and inventory management",
      "Laboratory information system integration",
      "Staff scheduling and management",
    ],
  },
  {
    title: "Telemedicine Platform",
    description:
      "Virtual healthcare delivery platform connecting patients with healthcare providers for remote consultations.",
    features: [
      "Secure video consultations with end-to-end encryption",
      "Digital prescription generation and delivery",
      "Patient health monitoring and data sharing",
      "Integration with wearable health devices",
      "Appointment scheduling and payment processing",
      "Medical record access and sharing",
    ],
  },
  {
    title: "Clinical Decision Support System",
    description:
      "AI-powered system that assists healthcare providers in making informed clinical decisions based on patient data.",
    features: [
      "Diagnostic assistance with symptom analysis",
      "Treatment recommendation based on clinical guidelines",
      "Drug interaction and allergy alerts",
      "Predictive analytics for patient outcomes",
      "Evidence-based medicine integration",
      "Continuous learning from new medical research",
    ],
  },
]

export const fitnessIndustry = [
  {
    title: "Gym Management Software",
    description: "Complete solution for fitness centers to manage memberships, classes, and facility operations.",
    features: [
      "Membership management with automated billing",
      "Class scheduling and attendance tracking",
      "Staff management and payroll integration",
      "Equipment maintenance scheduling",
      "Member check-in and access control",
      "Performance metrics and business analytics",
    ],
  },
  {
    title: "Fitness Tracking App",
    description:
      "Mobile application for users to track workouts, nutrition, and fitness progress with personalized recommendations.",
    features: [
      "Workout plan creation and tracking",
      "Nutrition logging and meal planning",
      "Progress visualization with charts and metrics",
      "Integration with wearable fitness devices",
      "Community features and challenges",
      "AI-powered workout recommendations",
    ],
  },
  {
    title: "Virtual Training Platform",
    description:
      "Online platform connecting fitness trainers with clients for virtual training sessions and coaching.",
    features: [
      "Live video training sessions with feedback",
      "On-demand workout library with various categories",
      "Client progress tracking and assessment tools",
      "Subscription management and payment processing",
      "Trainer-client messaging and communication",
      "Customizable workout program creation",
    ],
  },
]

export const bankAndFinanceIndustry = [
  {
    title: "Core Banking System",
    description:
      "Centralized banking platform that manages accounts, transactions, and essential banking operations.",
    features: [
      "Account management and processing",
      "Transaction processing and reconciliation",
      "Interest calculation and fee management",
      "Regulatory compliance and reporting",
      "Multi-currency support and exchange",
      "Loan origination and servicing",
    ],
  },
  {
    title: "Digital Banking Platform",
    description:
      "Omnichannel platform providing customers with seamless banking experiences across web and mobile devices.",
    features: [
      "Secure online and mobile banking interfaces",
      "Bill payment and fund transfer capabilities",
      "Personal financial management tools",
      "Biometric authentication and security features",
      "Push notifications and alerts",
      "Card management and control",
    ],
  },
  {
    title: "Fraud Detection System",
    description:
      "AI-powered system that monitors transactions in real-time to detect and prevent fraudulent activities.",
    features: [
      "Real-time transaction monitoring and analysis",
      "Behavioral analytics to identify suspicious patterns",
      "Automated alerts and case management",
      "Machine learning models that adapt to new fraud tactics",
      "Multi-factor authentication integration",
      "Compliance with financial security standards",
    ],
  },
]

export const ecommerceIndustry = [
  {
    title: "E-commerce Platform",
    description: "Complete online store solution with product management, shopping cart, and checkout functionality.",
    features: [
      "Product catalog management with variants",
      "Secure payment gateway integration",
      "Order management and fulfillment tracking",
      "Customer account management and wishlist",
      "SEO optimization tools",
      "Mobile-responsive storefronts",
    ],
  },
  {
    title: "Inventory Management System",
    description: "System for tracking inventory levels, orders, sales, and deliveries for online retailers.",
    features: [
      "Real-time inventory tracking across multiple channels",
      "Automated reordering based on stock thresholds",
      "Barcode and QR code scanning capabilities",
      "Warehouse management and location tracking",
      "Supplier management and purchase orders",
      "Inventory forecasting and analytics",
    ],
  },
  {
    title: "Customer Relationship Management",
    description:
      "E-commerce focused CRM for managing customer interactions, marketing campaigns, and loyalty programs.",
    features: [
      "Customer segmentation and targeting",
      "Personalized marketing automation",
      "Customer support ticket management",
      "Purchase history analysis and recommendations",
      "Loyalty program management",
      "Social media integration and monitoring",
    ],
  },
]

export const erpIndustry = [
  {
    title: "Enterprise Resource Planning",
    description: "Integrated management of core business processes in real-time across the entire organization.",
    features: [
      "Financial management and accounting",
      "Human resources and payroll processing",
      "Supply chain and procurement management",
      "Business intelligence and reporting",
      "Asset management and maintenance",
      "Customer relationship management",
    ],
  },
  {
    title: "Manufacturing ERP",
    description:
      "Specialized ERP system for manufacturing companies to manage production, inventory, and quality control.",
    features: [
      "Production planning and scheduling",
      "Bill of materials and product configuration",
      "Shop floor control and work order management",
      "Quality assurance and compliance tracking",
      "Equipment maintenance and downtime tracking",
      "Material requirements planning (MRP)",
    ],
  },
  {
    title: "Project Management ERP",
    description: "ERP module focused on project planning, execution, and monitoring for service-based organizations.",
    features: [
      "Project planning and resource allocation",
      "Time and expense tracking",
      "Budget management and cost control",
      "Client billing and invoicing automation",
      "Project portfolio management",
      "Team collaboration and document sharing",
    ],
  },
]

